### ISSUE TITLE
Support for subproject's located outside the workspace path

### ISSUE THREAD

**Issue by chenyunguiMilook** [krzysztofzablocki/KZLinkedConsole#12]

**Comment by krzysztofzablocki** [comment]
I'm assuming your subproject is not under workspace path of the main project ? that is problematic to solve, I think the only real way to support it properly would be to use xcode paths from the project settings which is not so straightforward afaik

**Comment by chenyunguiMilook** [comment]
That's true, Thanks for your reply :)

**Comment by ewanmellor** [comment]
Please see PR #14 .  This doesn't precisely meet the request here, but I think that it should be good enough (and it's certainly closer than the current behavior).

**Comment by krzysztofzablocki** [comment]
@chenyunguiMilook give it a try, I think it's a good progress :)

**Comment by chenyunguiMilook** [comment]
@krzysztofzablocki wow, It's working perfectly. super exciting :+1:
