### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by ivnsch** [krzysztofzablocki/KZLinkedConsole#24]
I installed the plugin using Alcatraz and building the project, none is working. Restarted Xcode and ensured the plugin was removed before installing it again.

I'm using QorumLogs and set `QorumLogs.KZLinkedConsoleSupportEnabled = true` in AppDelegate, the logs work fine but nothing is clickable. The plugin is listed as installed.

The log lines look like this
ListItemProviderImpl.swift:260 add(_:list:note:order:_:): blablabla

But I also did a test without QorumLogs using the function in the readme

```
func logMessage(message: String, filename: String = __FILE__, line: Int = __LINE__, function: String = __FUNCTION__) {
    print("\((filename as NSString).lastPathComponent):\(line) \(function):\r\(message)")
}
logMessage("blablablbla!!!")
```

And I see:

AppDelegate.swift:68 configLog():
blablablbla!!!

which is also not clickable.

What can be the problem? I'm using Xcode 7.0

Thanks

**Comment by nickdoherty** [comment]
I'm having the same issue. XCGLogger as well as the logMessage function fails to link to a file.

XCode 7.2.1

**Comment by skreutzberger** [comment]
Guys, with [SwiftyBeaver](https://github.com/SwiftyBeaver/SwiftyBeaver) it should work.

**Comment by ivnsch** [comment]
Not sure why changing the logger would fix it? The direct print also doesn't work.

**Comment by skreutzberger** [comment]
ah,I get it, that is weird.

**Comment by krzysztofzablocki** [comment]
I think last commit regex messed stuff up, let me reverse it as it only does optimization, which we can do later

**Comment by krzysztofzablocki** [comment]
@i-schuetz can you try the current master ? I reversed last commit

**Comment by nickdoherty** [comment]
Uninstalled, reinstalled to current master. It works! Thanks @krzysztofzablocki

**Comment by ivnsch** [comment]
It works with master, thanks!
