### ISSUE TITLE
Objective c compatibility 

### ISSUE THREAD

**Issue by paultnp** [krzysztofzablocki/KZLinkedConsole#28]
This plugin works perfect in swift project, however it is not working with Objective-C. I have also tried to create a swift file in Objective-C project and added the method "logMessage" given in your sample code but the hyperlink in the log did not create.

Please let me know if this plugin can be integrated with objective-c project as it is very useful plugin and must be available for objective-c projects

Thanks in advanced.

**Comment by krzysztofzablocki** [comment]
@paultnp I'm assuming you got it to work ? :)

**Comment by paultnp** [comment]
Yes, Thanks
