### ISSUE TITLE
Can not work with SwiftyBeaver

### ISSUE THREAD

**Issue by roshanman** [krzysztofzablocki/KZLinkedConsole#34]
when function no arguments like this： 
    ChatListViewController.userStatusChanged:212 
    BaseDataTask.deinit:229

our plugin can not work good.

**Comment by skreutzberger** [comment]
Hi, Sebastian here from SwiftyBeaver. I can confirm that the latest KZLinkedConsole is working fine with the latest SwiftyBeaver logging framework so maybe can close that older issue. We had some improvements in how files and functions are displayed in the Xcode Console and they should have fixed all potential glitches.

Here is a short GIF which shows the working latest SwiftyBeaver + KZLinkedConsole:
[http://g.recordit.co/gbRgw72RiI.gif](http://g.recordit.co/gbRgw72RiI.gif)

**Comment by krzysztofzablocki** [comment]
glad to hear that :)
