### ISSUE TITLE
Sometimes opens links in a separate window

### ISSUE THREAD

**Issue by grigorye** [krzysztofzablocki/KZLinkedConsole#35]
Somehow clicking a link in console started to open the corresponding file in a separate window not in the current editor window. I found that it's due to similar file existing in the source directory. Sometime ago I had BitTorrent Sync (https://getsync.com/) installed, and enabled syncing the source directory. It turns out that clicking the links revealed the files from (hidden) .sync subdirectory that contained copies of the source files. Removing that directory resolved the problem.

**Comment by brentleyjones** [comment]
I think this is related to #31.

**Comment by grigorye** [comment]
@brentleyjones Correct, it looks like the same issue.
