### ISSUE TITLE
Not work with CocoaLumberjack

### ISSUE THREAD

**Issue by CyrusNG** [krzysztofzablocki/KZLinkedConsole#4]
I rewrite one formatter to make the specific format the plugin need with CocoaLumberjack , but not work. my xCode is 6.4 and 7.1.1 with xCodeColor plugin.
Log Detail:
2015-12-09 16:28:28:963 [WARN] | AppDelegate.m:90: [application:didFinishLaunchingWithOptions:]: Testing!!!!!!!!!!!!

**Comment by krzysztofzablocki** [comment]
you need to be a little bit more specific, does it highlight the text?

**Comment by CyrusNG** [comment]
I mean AppDelegate.m:90 is NOT a link. It can NOT clickable.

**Comment by krzysztofzablocki** [comment]
are you sure the plugin is loaded? did you have to click allow plugin?

**Comment by GuyKahlon** [comment]
Hi, it doesn't work for me also. 
I installed the Plugin via Alcatraz.
I use with Xcode Version 7.1.1 (7B1005) and CocoaLumberjack.
I can see the Log messages in the console but they aren't clickable.

Can you assist pleas?

My Code:

import Foundation
import CocoaLumberjack
import CocoaLumberjack.DDDispatchQueueLogFormatter

class MyLogger {

```
class func initializLogger(logLevel: DDLogLevel = .Debug){

  #if DEBUG
      defaultDebugLevel = logLevel
  #else
      defaultDebugLevel = .Off
  #endif

  DDLog.addLogger(DDASLLogger.sharedInstance()) //Logger for the Apple system log facility
  DDLog.addLogger(DDTTYLogger.sharedInstance()) //Logger for Terminal output/Xcode console
  DDTTYLogger.sharedInstance().colorsEnabled = true
  DDTTYLogger.sharedInstance().setForegroundColor(UIColor.greenColor(), backgroundColor: nil, forFlag: .Info)
  DDTTYLogger.sharedInstance().setForegroundColor(UIColor.magentaColor(), backgroundColor: nil, forFlag: .Debug)
  DDTTYLogger.sharedInstance().logFormatter = KZFormatter()
}
```

}

class KZFormatter: DDDispatchQueueLogFormatter {

  lazy var formatter: NSDateFormatter = {
    let dateFormatter = NSDateFormatter()
    dateFormatter.formatterBehavior = .Behavior10_4
    dateFormatter.dateFormat = "HH:mm:ss.SSS"
    return dateFormatter
  }()

  override func formatLogMessage(logMessage: DDLogMessage!) -> String {
    let dateAndTime = formatter.stringFromDate(logMessage.timestamp)

```
var logLevel: String
let logFlag = logMessage.flag
if logFlag.contains(.Error) {
  logLevel = "ERR"
} else if logFlag.contains(.Warning){
  logLevel = "WRN"
} else if logFlag.contains(.Info) {
  logLevel = "INF"
} else if logFlag.contains(.Debug) {
  logLevel = "DBG"
} else if logFlag.contains(.Verbose) {
  logLevel = "VRB"
} else {
  logLevel = "???"
}

let formattedLog = "\(dateAndTime) |\(logLevel)| \((logMessage.file as NSString).lastPathComponent):\(logMessage.line): ( \(logMessage.function) ): \(logMessage.message)"
return formattedLog;
```

  }
}

**Comment by GuyKahlon** [comment]
How can I check if the plugin is allow? I loaded the bundle after reset the Xcode!

**Comment by CyrusNG** [comment]
I also wanna know how I can check the plugin is allow.
And, I also installed the Plugin via Alcatraz.
please help.

**Comment by krzysztofzablocki** [comment]
When you remove the plugin and then reinstall it, xcode should ask if you allow to load the package. Can you try reinstalling?

**Comment by CyrusNG** [comment]
Tried and click "load bundle", but still not work.

**Comment by GuyKahlon** [comment]
Ok, After reinstall works great for a device, but doesn't work for a simulator.

**Comment by krzysztofzablocki** [comment]
@GuyKahlon can you run it from xcode and see where is it not going through on simulator for you ? something in KZLinkedConsole.swift or NSTextStorage+Extensions must be failing if you are not getting highlighted links

**Comment by GuyKahlon** [comment]
Checking...

**Comment by CyrusNG** [comment]
If I don't use lastPathComponent, how can I get file name?

**Comment by krzysztofzablocki** [comment]
I've updated the plugin, try reinstalling and see if it works now?

**Comment by CyrusNG** [comment]
It's ok now. This plugin is very cool, it can help me debug easier. Thanks.

**Comment by krzysztofzablocki** [comment]
awesome ;)

**Comment by GuyKahlon** [comment]
@krzysztofzablocki Thanks for this awesome plugin.

**Comment by krzysztofzablocki** [comment]
happy I was able to solve the issue for you guys :)
