### ISSUE TITLE
Not working if using lastPathComponent

### ISSUE THREAD

**Issue by kenji21** [krzysztofzablocki/KZLinkedConsole#6]
Works :

```
#define OKLog(s,...) NSLog( @"%s:%d: %p %@/%@\n%@", __FILE__, __LINE__, self, NSStringFromClass([self class]), NSStringFromSelector(_cmd), [NSString stringWithFormat:(s), ##__VA_ARGS__] )
```

outputs :

```
2015-12-09 12:58:58.686 App[67338:2289954] /Users/kenji/source-cache/app/Classes/AppDelegate.m:73: 0x7fba8c8f3210 AppDelegate/application:didFailToRegisterForRemoteNotificationsWithError:
```

Don't work :

```
#define OKLog(s,...) NSLog( @"%@:%d: %p %@/%@\n%@", [[NSString stringWithUTF8String:__FILE__] lastPathComponent], __LINE__, self, NSStringFromClass([self class]), NSStringFromSelector(_cmd), [NSString stringWithFormat:(s), ##__VA_ARGS__] )
```

```
2015-12-09 12:57:49.728 CFFlux[66697:2287745] AppDelegate.m:73: 0x7fd418732120 AppDelegate/application:didFailToRegisterForRemoteNotificationsWithError:
```

The only difference between first and second OKLog define is for the first parameter which changed from 
`__FILE__` to  `[[NSString stringWithUTF8String:__FILE__] lastPathComponent]`

The issue is that I don't want to have the full file path in the output. But it may be difficult to find corresponding file in the project.

**Comment by kenji21** [comment]
Looking at the GIF in your blog post didn't show the full path... is another plugin removing the path ?

**Comment by krzysztofzablocki** [comment]
ah crap I think it's same issue as #4 and it's the find that is not working, can you put a breakpoint and see if there is a workspacePath and what it's value is (NSTextStorage+Extension) injectLinksIntoLogs?

**Comment by kenji21** [comment]
Looks good :

Printing description of path:
"/Users/kenji/source-cache/app"

**Comment by krzysztofzablocki** [comment]
It's missing /Classes in the composed path though ?

**Comment by kenji21** [comment]
Hmm... i've created another "blank" project, to copy the define inside and it works with lastPathComponent. I'm investigating.

**Comment by krzysztofzablocki** [comment]
@kenji21 when you investigate could you record:
- workspacePath from line 59 in KZPluginHelper
- path from line 41 in TextStorage+Extension
- result from 52 in TextStorage

I might have missed some case that breaks connections there

**Comment by kenji21** [comment]
From line 59, got nil :

```
(lldb) po workspace?.valueForKeyPath("representingFilePath._pathString")
nil
```

**Comment by kenji21** [comment]
And sometimes it's OK :

```
(lldb) po workspace?.valueForKeyPath("representingFilePath._pathString")
▿ Optional(/Users/kenji/source-cache/app/App.xcodeproj)
```

**Comment by kenji21** [comment]
And then, no matches at pattern.matchesInString at NSTextStorage+Extensions:45

**Comment by kenji21** [comment]
OK, i comment too quickly, the no match was due to a third party library log...

**Comment by kenji21** [comment]
now it works... unbelievable

(lldb) po result
"/Users/kenji/source-cache/app/App/AppDelegate.m"

**Comment by krzysztofzablocki** [comment]
so the point of failure looks like the workspacePath ?

**Comment by kenji21** [comment]
I'm sure to have restarted xcode after having built your plugin (had the "load bundle" alert). now it works, i'll post again if it doesn't work after installing the plugin on a teammate mac.

**Comment by krzysztofzablocki** [comment]
@kenji21 I update the plugin, can you reinstall and give it a try, should be more stable

**Comment by kenji21** [comment]
Installed on a second mac. no issue with the same project on this one.
My teammate was having a suggestion : same feature from a stacktrace... (a little harder because no filename, and crash can be in a class extension)

**Comment by krzysztofzablocki** [comment]
@kenji21 was he running the updated version? I think this one is more stable because it fixed #4

**Comment by kenji21** [comment]
was running at commit 26b60febbb77a5dd3a1bb97c6ea646e76b7da065

**Comment by krzysztofzablocki** [comment]
ok, try with updated, I'm closing this but if you see it happening let me know and we'll reopen

**Comment by kenji21** [comment]
sure, thanks for support (and many thanks for this great plugin, vote up to have it directly inside xcode)

**Comment by oldtrafford91** [comment]
how I can strip file path with only file name

**Comment by kenji21** [comment]
@oldtrafford91 simply with this code : `[[NSString stringWithUTF8String:__FILE__] lastPathComponent]`

@krzysztofzablocki updated to current HEAD, restarted xcode, no issue.
