### ISSUE TITLE
No working with Objective-C?

### ISSUE THREAD

**Issue by oldtrafford91** [krzysztofzablocki/KZLinkedConsole#7]

**Comment by krzysztofzablocki** [comment]
language doesn't matter

**Comment by oldtrafford91** [comment]
My logging function:
    NSLog(@"%s:%s",**FILE**,**PRETTY_FUNCTION**);
Is this wrong?

**Comment by krzysztofzablocki** [comment]
what's the output?

**Comment by oldtrafford91** [comment]
It log the file path and function but not clickable

**Comment by krzysztofzablocki** [comment]
is it higlighted in console ?

**Comment by oldtrafford91** [comment]
No

**Comment by krzysztofzablocki** [comment]
see #6 as we are discussing possible issue that some people might be facing
