### ISSUE TITLE
Automatic Background Color

### ISSUE THREAD

**Issue by skreutzberger** [krzysztofzablocki/KZLinkedConsole#9]
Hi, can you auto-detect the Xcode background color and if it is dark then maybe use a bright font color and if it bright then use blue font?

Or maybe even much simpler:
Can you use the currently used console font but **just make the link underlined**? I think that should be enough to make the link stand out and visible. Because if you add a background color and text color then it really looks messy for users with custom themes.

For example, here is my Xcode console:

<img width="874" alt="colorscreen" src="https://cloud.githubusercontent.com/assets/564725/11713274/b6dd32ee-9f32-11e5-8302-3671c120f78c.png">

**Comment by krzysztofzablocki** [comment]
I have dark theme, that's why I added the background white color, because to be able to change color of a link would require to change it on the whole console NSTextView as far as I'm aware

**Comment by skreutzberger** [comment]
Can you detect the standard foreground and background color of "normal" text and then just set the link in that color?

I am not an Objective-C expert (even not a beginner  ...) but maybe these links could help you?
http://stackoverflow.com/questions/17262251/nstextview-custom-link-color-for-range
http://shapeof.com/archives/2010/12/customizing_links_in_an_nstextview.html
http://jaanus.com/how-to-easily-present-strings-with-bold-text-and-links-in-cocoa/

**Comment by skreutzberger** [comment]
Or is that color an Xcode theme setting somewhere? I can’t find it :(

**Comment by krzysztofzablocki** [comment]
this should make it look good

**Comment by krzysztofzablocki** [comment]
@skreutzberger just update to new version, it will keep your theme styling now, and thanks for asking about it :+1: looks better

**Comment by skreutzberger** [comment]
perfect, I'm glad to help :)
